import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, ChevronLeft, ChevronRight, ImageOff, Loader2, Phone, ShieldCheck, X } from "lucide-react";
import { supabase } from "../../lib/supabase";

interface RentalDrone { id:number; name:string; description:string|null; image_url:string|null; daily_price:number; deposit_amount:number; is_active:boolean; created_at:string; }
interface RentalBooking { id:number; rental_drone_id:number; customer_name:string; phone:string; start_date:string; end_date:string; total_days:number; daily_price:number; total_amount:number; status:string; notes:string|null; created_at:string; }
const MONTHS=["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"];
const WEEK=["أحد","اثن","ثلا","أرب","خمي","جمع","سبت"];
const ACTIVE=["pending","confirmed","active"];

function normalizePhoneNumber(value:string){const a="٠١٢٣٤٥٦٧٨٩",p="۰۱۲۳۴۵۶۷۸۹";return value.replace(/[٠-٩]/g,d=>String(a.indexOf(d))).replace(/[۰-۹]/g,d=>String(p.indexOf(d))).replace(/\D/g,"");}
function key(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function parse(v:string){const [y,m,d]=v.split("-").map(Number);return new Date(y,m-1,d);}
function today(){const d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate());}
function days(a:string,b:string){return Math.max(1,Math.round((parse(b).getTime()-parse(a).getTime())/86400000)+1);}
function overlap(a:string,b:string,c:string,d:string){return a<=d&&b>=c;}

export default function Rentals(){
 const now=useMemo(()=>today(),[]),[drones,setDrones]=useState<RentalDrone[]>([]),[bookings,setBookings]=useState<RentalBooking[]>([]);
 const [selected,setSelected]=useState<RentalDrone|null>(null),[month,setMonth]=useState(new Date(now.getFullYear(),now.getMonth(),1));
 const [start,setStart]=useState(""),[end,setEnd]=useState(""),[name,setName]=useState(""),[phone,setPhone]=useState(""),[notes,setNotes]=useState("");
 const [loading,setLoading]=useState(true),[loadingDates,setLoadingDates]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState<RentalBooking|null>(null);
 useEffect(()=>{void loadDrones();},[]);
 async function loadDrones(){setLoading(true);const r=await supabase.from("rental_drones").select("*").eq("is_active",true).order("created_at",{ascending:false});if(r.error){setError("تعذر تحميل درونات الإيجار. شغّل ملف SQL أولًا.");setDrones([]);}else setDrones((r.data as RentalDrone[])||[]);setLoading(false);}
 async function open(d:RentalDrone){setSelected(d);setStart("");setEnd("");setError("");setSuccess(null);setMonth(new Date(now.getFullYear(),now.getMonth(),1));setLoadingDates(true);const r=await supabase.from("rental_bookings").select("*").eq("rental_drone_id",d.id).in("status",ACTIVE);if(r.error){setError("تعذر تحميل التواريخ المحجوزة");setBookings([]);}else setBookings((r.data as RentalBooking[])||[]);setLoadingDates(false);}
 const cells=useMemo(()=>{const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay(),total=new Date(y,m+1,0).getDate(),a:(Date|null)[]=[];for(let i=0;i<first;i++)a.push(null);for(let i=1;i<=total;i++)a.push(new Date(y,m,i));while(a.length%7)a.push(null);return a;},[month]);
 const booked=(v:string)=>bookings.some(b=>ACTIVE.includes(b.status)&&v>=b.start_date&&v<=b.end_date);
 const available=(a:string,b:string)=>!bookings.some(x=>ACTIVE.includes(x.status)&&overlap(a,b,x.start_date,x.end_date));
 function choose(d:Date){const v=key(d);if(d<now||booked(v))return;setError("");if(!start||end){setStart(v);setEnd("");return;}if(v<start){setStart(v);setEnd("");return;}if(!available(start,v)){setError("يوجد حجز داخل هذه المدة. اختر مدة أخرى.");return;}setEnd(v);}
 function move(n:number){const x=new Date(month.getFullYear(),month.getMonth()+n,1),min=new Date(now.getFullYear(),now.getMonth(),1);if(x>=min)setMonth(x);}
 const count=start&&end?days(start,end):0,total=selected?Number(selected.daily_price)*count:0;
 async function submit(e:React.FormEvent){e.preventDefault();if(!selected)return;const ph=normalizePhoneNumber(phone);if(!name.trim()){setError("اكتب اسم المستأجر");return;}if(ph.length<8){setError("اكتب رقم هاتف صحيح");return;}if(!start||!end){setError("اختر تاريخ البداية والنهاية");return;}setSaving(true);setError("");
 const check=await supabase.from("rental_bookings").select("id").eq("rental_drone_id",selected.id).in("status",ACTIVE).lte("start_date",end).gte("end_date",start);
 if(check.error){setError("تعذر التأكد من توفر التاريخ");setSaving(false);return;}if((check.data||[]).length){setError("هذه المدة أصبحت محجوزة. اختر مدة أخرى.");setSaving(false);return;}
 const payload={rental_drone_id:selected.id,customer_name:name.trim(),phone:ph.startsWith("968")?ph:`968${ph}`,start_date:start,end_date:end,total_days:count,daily_price:Number(selected.daily_price),total_amount:total,status:"pending",notes:notes.trim()||null};
 const r=await supabase.from("rental_bookings").insert(payload).select("*").single();if(r.error){setError("حدث خطأ أثناء إرسال الحجز أو يوجد تعارض بالتاريخ");}else{setSuccess(r.data as RentalBooking);setBookings(v=>[...v,r.data as RentalBooking]);setName("");setPhone("");setNotes("");}setSaving(false);}
 return <div className="min-h-screen bg-[#F8F7F2] px-4 py-10 text-[#0F3A2B]" dir="rtl"><div className="mx-auto max-w-7xl">
 <section className="mb-10 rounded-[36px] bg-[#0F3A2B] px-6 py-12 text-center text-white shadow-xl"><CalendarDays className="mx-auto mb-4 h-12 w-12 text-[#E5D8AA]"/><h1 className="text-4xl font-black md:text-5xl">تأجير الدرونات</h1><p className="mx-auto mt-4 max-w-2xl text-white/80">اختر الدرون وحدد مدة الإيجار. الأيام المحجوزة تظهر تلقائيًا ولا يمكن اختيارها.</p></section>
 {error&&!selected&&<div className="mb-5 rounded-2xl bg-red-50 p-4 text-center font-bold text-red-700">{error}</div>}
 {loading?<div className="flex justify-center gap-2 py-20"><Loader2 className="animate-spin"/>جاري التحميل...</div>:drones.length===0?<div className="rounded-3xl bg-white p-12 text-center">لا توجد درونات متاحة حاليًا</div>:<div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-3">{drones.map(d=><article key={d.id} className="overflow-hidden rounded-[30px] border border-[#DED7C9] bg-white shadow-sm"><div className="aspect-[4/3] bg-[#F1EEE6]">{d.image_url?<img src={d.image_url} alt={d.name} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center"><ImageOff/></div>}</div><div className="p-6"><h2 className="text-2xl font-black">{d.name}</h2><p className="mt-3 min-h-[52px] text-sm leading-7 text-gray-600">{d.description||"درون متاح للإيجار اليومي."}</p><div className="mt-5 flex items-end justify-between border-t pt-5"><div><p className="text-xs text-gray-500">سعر اليوم</p><p className="text-2xl font-black">{Number(d.daily_price).toFixed(3)} ر.ع</p></div><button onClick={()=>void open(d)} className="rounded-full bg-[#0F3A2B] px-6 py-3 font-bold text-white">اختر واحجز</button></div></div></article>)}</div>}
 </div>
 {selected&&<div className="fixed inset-0 z-[9999] overflow-y-auto bg-black/55 p-3 backdrop-blur-sm"><div className="mx-auto my-3 max-w-6xl rounded-[32px] bg-[#F8F7F2] shadow-2xl"><div className="sticky top-0 z-20 flex items-center justify-between border-b bg-[#F8F7F2] px-6 py-4"><div><p className="text-xs text-gray-500">حجز درون</p><h2 className="text-2xl font-black">{selected.name}</h2></div><button onClick={()=>!saving&&setSelected(null)} className="rounded-full bg-white p-3"><X/></button></div>
 {success?<div className="mx-auto max-w-xl px-6 py-16 text-center"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-green-100 text-green-700"><Check className="h-10 w-10"/></div><h3 className="mt-6 text-3xl font-black">تم استلام طلب الإيجار</h3><p className="mt-3 text-gray-600">رقم الحجز #{success.id}. سنتواصل معك لتأكيد الحجز.</p><div className="mt-6 rounded-3xl bg-white p-5">من {success.start_date} إلى {success.end_date}<br/>{success.total_days} يوم — {Number(success.total_amount).toFixed(3)} ر.ع</div><button onClick={()=>setSelected(null)} className="mt-6 rounded-full bg-[#0F3A2B] px-10 py-4 font-bold text-white">إغلاق</button></div>:
 <div className="grid gap-6 p-5 lg:grid-cols-[1.25fr_.75fr]"><section className="rounded-[28px] border bg-white p-5"><div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-xl font-black">اختر مدة الإيجار</h3><p className="text-sm text-gray-500">اضغط تاريخ البداية ثم النهاية</p></div><div className="flex items-center gap-3 rounded-full bg-[#F8F7F2] p-1"><button onClick={()=>move(-1)} disabled={month.getFullYear()===now.getFullYear()&&month.getMonth()===now.getMonth()} className="rounded-full bg-white p-2 disabled:opacity-30"><ChevronRight/></button><strong className="min-w-[145px] text-center">{MONTHS[month.getMonth()]} {month.getFullYear()}</strong><button onClick={()=>move(1)} className="rounded-full bg-white p-2"><ChevronLeft/></button></div></div>
 {loadingDates?<div className="flex justify-center py-24"><Loader2 className="animate-spin"/></div>:<><div className="mb-2 grid grid-cols-7 gap-1 text-center text-xs text-gray-500">{WEEK.map(x=><div key={x}>{x}</div>)}</div><div className="grid grid-cols-7 gap-1 sm:gap-2">{cells.map((d,i)=>{if(!d)return <div key={i}/>;const v=key(d),b=booked(v),past=d<now,sel=v===start||v===end,inside=start&&end&&v>start&&v<end;return <button key={v} disabled={past||b} onClick={()=>choose(d)} className={`aspect-square rounded-xl border font-bold ${b?"bg-red-50 text-red-300 line-through":past?"bg-gray-50 text-gray-300":sel?"bg-[#0F3A2B] text-white":inside?"bg-[#F0E8CF]":"bg-white hover:border-[#0F3A2B]"}`}>{d.getDate()}</button>})}</div><div className="mt-4 text-xs text-gray-500">الأحمر محجوز — الرمادي غير متاح</div></>}
 </section><aside><div className="mb-5 rounded-[28px] border bg-white p-5"><h3 className="text-2xl font-black">{selected.name}</h3><p className="mt-2 text-sm text-gray-600">{selected.description}</p><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#F8F7F2] p-3">اليومي<br/><b>{Number(selected.daily_price).toFixed(3)} ر.ع</b></div><div className="rounded-2xl bg-[#F8F7F2] p-3">التأمين<br/><b>{Number(selected.deposit_amount||0).toFixed(3)} ر.ع</b></div></div></div>
 <form onSubmit={submit} className="rounded-[28px] border bg-white p-5"><h3 className="mb-4 text-xl font-black">بيانات الحجز</h3><input value={name} onChange={e=>setName(e.target.value)} placeholder="الاسم الكامل" className="mb-3 h-12 w-full rounded-2xl border bg-[#F8F7F2] px-4"/><div className="mb-3 flex items-center gap-2 rounded-2xl border bg-[#F8F7F2] px-4" dir="ltr"><Phone className="h-4 w-4"/><input value={phone} onChange={e=>setPhone(normalizePhoneNumber(e.target.value))} placeholder="968XXXXXXXX" className="h-12 w-full bg-transparent outline-none"/></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="ملاحظات" className="min-h-20 w-full rounded-2xl border bg-[#F8F7F2] p-4"/>
 <div className="mt-4 rounded-2xl bg-[#F8F7F2] p-4 text-sm"><div>من: <b>{start||"لم يحدد"}</b></div><div>إلى: <b>{end||"لم يحدد"}</b></div><div>الأيام: <b>{count}</b></div><div className="mt-3 border-t pt-3 text-lg">الإجمالي: <b>{total.toFixed(3)} ر.ع</b></div></div>{error&&<div className="mt-3 rounded-2xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}<button disabled={saving||!start||!end} className="mt-4 flex h-14 w-full items-center justify-center gap-2 rounded-full bg-[#0F3A2B] font-black text-white disabled:opacity-50">{saving?<Loader2 className="animate-spin"/>:<ShieldCheck/>}إرسال طلب الحجز</button></form></aside></div>}
 </div></div>}
 </div>;
}
