-- Create the products table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    "nameAr" TEXT NOT NULL,
    category TEXT NOT NULL,
    "categoryAr" TEXT NOT NULL,
    "retailPrice" NUMERIC NOT NULL,
    "wholesalePrice" NUMERIC NOT NULL,
    "costPrice" NUMERIC,
    "discountPercentage" NUMERIC,
    image TEXT NOT NULL,
    "additionalImages" TEXT[],
    description TEXT,
    "descriptionAr" TEXT,
    stock INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Force add columns if they were missing from previous creation
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='costPrice') THEN
        ALTER TABLE public.products ADD COLUMN "costPrice" NUMERIC;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='discountPercentage') THEN
        ALTER TABLE public.products ADD COLUMN "discountPercentage" NUMERIC;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='additionalImages') THEN
        ALTER TABLE public.products ADD COLUMN "additionalImages" TEXT[];
    END IF;
END $$;

-- Enable Row Level Security
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any to avoid errors
DROP POLICY IF EXISTS "Allow public read access to products" ON public.products;
DROP POLICY IF EXISTS "Allow authenticated full access to products" ON public.products;
DROP POLICY IF EXISTS "Allow public full access to products" ON public.products;

-- Allow completely public access for testing purposes
CREATE POLICY "Allow public full access to products" ON public.products FOR ALL USING (true) WITH CHECK (true);

-- Create profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) PRIMARY KEY,
    email TEXT NOT NULL,
    full_name TEXT NOT NULL,
    role TEXT DEFAULT 'user'::text,
    "businessName" TEXT,
    "taxId" TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
-- Drop existing policies if any to avoid errors
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;

CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id OR auth.uid() IS NULL);

-- Create orders table
CREATE TABLE IF NOT EXISTS public.orders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    status TEXT DEFAULT 'pending',
    total_price NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own orders" ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Create order items table
CREATE TABLE IF NOT EXISTS public.order_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id),
    quantity INTEGER NOT NULL,
    price NUMERIC NOT NULL,
    type TEXT NOT NULL,
    size JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own order items" ON public.order_items FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.orders WHERE public.orders.id = public.order_items.order_id AND public.orders.user_id = auth.uid())
);
CREATE POLICY "Users can insert own order items" ON public.order_items FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM public.orders WHERE public.orders.id = public.order_items.order_id AND public.orders.user_id = auth.uid())
);


-- Drone rentals
-- MERGAB Drone Rentals - run once in Supabase SQL Editor
create table if not exists public.rental_drones (
 id bigint generated by default as identity primary key,
 name text not null, description text, image_url text,
 daily_price numeric(12,3) not null default 0 check(daily_price>=0),
 deposit_amount numeric(12,3) not null default 0 check(deposit_amount>=0),
 is_active boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.rental_bookings (
 id bigint generated by default as identity primary key,
 rental_drone_id bigint not null references public.rental_drones(id) on delete restrict,
 customer_name text not null, phone text not null,
 start_date date not null, end_date date not null,
 total_days integer not null check(total_days>0),
 daily_price numeric(12,3) not null check(daily_price>=0),
 total_amount numeric(12,3) not null check(total_amount>=0),
 status text not null default 'pending' check(status in('pending','confirmed','active','completed','cancelled')),
 notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 constraint rental_booking_date_order check(end_date>=start_date)
);
create index if not exists rental_bookings_drone_dates_idx on public.rental_bookings(rental_drone_id,start_date,end_date);
create or replace function public.prevent_rental_booking_overlap() returns trigger language plpgsql as $$
begin
 if new.status in('pending','confirmed','active') and exists(
  select 1 from public.rental_bookings b where b.rental_drone_id=new.rental_drone_id
  and b.id<>coalesce(new.id,0) and b.status in('pending','confirmed','active')
  and daterange(b.start_date,b.end_date,'[]') && daterange(new.start_date,new.end_date,'[]')
 ) then raise exception 'Rental booking date overlap'; end if;
 new.total_days := (new.end_date-new.start_date)+1;
 new.total_amount := new.total_days*new.daily_price;
 new.updated_at := now(); return new;
end $$;
drop trigger if exists rental_booking_overlap_trigger on public.rental_bookings;
create trigger rental_booking_overlap_trigger before insert or update of rental_drone_id,start_date,end_date,status,daily_price on public.rental_bookings for each row execute function public.prevent_rental_booking_overlap();
alter table public.rental_drones enable row level security;
alter table public.rental_bookings enable row level security;
drop policy if exists "Rental drones public access temporary" on public.rental_drones;
create policy "Rental drones public access temporary" on public.rental_drones for all to public using(true) with check(true);
drop policy if exists "Rental bookings public access temporary" on public.rental_bookings;
create policy "Rental bookings public access temporary" on public.rental_bookings for all to public using(true) with check(true);
insert into storage.buckets(id,name,public) values('rental-images','rental-images',true) on conflict(id) do update set public=true;
drop policy if exists "Rental images select" on storage.objects;
create policy "Rental images select" on storage.objects for select to public using(bucket_id='rental-images');
drop policy if exists "Rental images insert temporary" on storage.objects;
create policy "Rental images insert temporary" on storage.objects for insert to public with check(bucket_id='rental-images');
drop policy if exists "Rental images update temporary" on storage.objects;
create policy "Rental images update temporary" on storage.objects for update to public using(bucket_id='rental-images') with check(bucket_id='rental-images');
drop policy if exists "Rental images delete temporary" on storage.objects;
create policy "Rental images delete temporary" on storage.objects for delete to public using(bucket_id='rental-images');
-- Important: temporary public policies match the current sessionStorage admin system.
-- Move admin to Supabase Auth later, then restrict update/delete/select of customer data to admin users.
