import { useEffect, useMemo, useState } from "react";
import { CalendarDays, ImagePlus, Loader2, Pencil, Plus, RefreshCw, Trash2, X } from "lucide-react";
import { supabase } from "../../../lib/supabase";
interface Drone{id:number;name:string;description:string|null;image_url:string|null;daily_price:number;deposit_amount:number;is_active:boolean;created_at:string;updated_at:string}
interface Booking{id:number;rental_drone_id:number;customer_name:string;phone:string;start_date:string;end_date:string;total_days:number;daily_price:number;total_amount:number;status:string;notes:string|null;created_at:string;rental_drones?:{name?:string|null}|null}
const STAT=[["pending","قيد المراجعة"],["confirmed","مؤكد"],["active","قيد الإيجار"],["completed","مكتمل"],["cancelled","ملغي"]] as const;
const label=(v:string)=>STAT.find(x=>x[0]===v)?.[1]||v;
const style=(v:string)=>v==="pending"?"bg-yellow-100 text-yellow-800":v==="confirmed"?"bg-blue-100 text-blue-800":v==="active"?"bg-purple-100 text-purple-800":v==="completed"?"bg-green-100 text-green-800":"bg-red-100 text-red-800";
export default function RentalManager(){const [drones,setDrones]=useState<Drone[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[section,setSection]=useState<"bookings"|"drones">("bookings"),[show,setShow]=useState(false),[edit,setEdit]=useState<number|null>(null),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[selected,setSelected]=useState<Booking|null>(null);
 const empty={name:"",description:"",image_url:"",daily_price:"",deposit_amount:"0",is_active:true};const [form,setForm]=useState(empty);
 useEffect(()=>{void load();const c=supabase.channel("rental-admin").on("postgres_changes",{event:"*",schema:"public",table:"rental_bookings"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(c)}},[]);
 async function load(){setLoading(true);const [d,b]=await Promise.all([supabase.from("rental_drones").select("*").order("created_at",{ascending:false}),supabase.from("rental_bookings").select("*, rental_drones(name)").order("created_at",{ascending:false})]);if(d.error||b.error)setError("تعذر تحميل بيانات الإيجار. شغّل ملف SQL الجديد.");else{setDrones((d.data as Drone[])||[]);setBookings((b.data as Booking[])||[])}setLoading(false)}
 const stats=useMemo(()=>{const valid=bookings.filter(b=>["confirmed","active","completed"].includes(b.status));const map=new Map<string,number>();valid.forEach(b=>{const n=b.rental_drones?.name||"غير معروف";map.set(n,(map.get(n)||0)+1)});return{revenue:valid.reduce((s,b)=>s+Number(b.total_amount||0),0),days:valid.reduce((s,b)=>s+Number(b.total_days||0),0),pending:bookings.filter(b=>b.status==="pending").length,active:bookings.filter(b=>b.status==="active").length,top:[...map.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||"—"}},[bookings]);
 function create(){setEdit(null);setForm(empty);setShow(true);setError("")}function editDrone(d:Drone){setEdit(d.id);setForm({name:d.name,description:d.description||"",image_url:d.image_url||"",daily_price:String(d.daily_price),deposit_amount:String(d.deposit_amount),is_active:d.is_active});setShow(true)}
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(!["image/jpeg","image/png","image/webp"].includes(f.type)||f.size>5*1024*1024){setError("الصورة يجب أن تكون JPG/PNG/WEBP وأقل من 5MB");return}setUploading(true);const ext=f.name.split(".").pop()||"jpg",path=`drones/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const r=await supabase.storage.from("rental-images").upload(path,f);if(r.error)setError("فشل رفع الصورة");else{const u=supabase.storage.from("rental-images").getPublicUrl(path);setForm(x=>({...x,image_url:u.data.publicUrl}))}setUploading(false)}
 async function save(e:React.FormEvent){e.preventDefault();const p=Number(form.daily_price),dep=Number(form.deposit_amount||0);if(!form.name.trim()||p<=0||dep<0){setError("تأكد من الاسم والسعر والتأمين");return}setSaving(true);const payload={name:form.name.trim(),description:form.description.trim()||null,image_url:form.image_url||null,daily_price:p,deposit_amount:dep,is_active:form.is_active,updated_at:new Date().toISOString()};const r=edit===null?await supabase.from("rental_drones").insert(payload):await supabase.from("rental_drones").update(payload).eq("id",edit);if(r.error)setError(r.error.message);else{await load();setShow(false);setForm(empty)}setSaving(false)}
 async function status(id:number,v:string){const r=await supabase.from("rental_bookings").update({status:v,updated_at:new Date().toISOString()}).eq("id",id);if(r.error)setError(r.error.message);else{setBookings(a=>a.map(b=>b.id===id?{...b,status:v}:b));setSelected(s=>s?.id===id?{...s,status:v}:s)}}
 async function delDrone(d:Drone){if(!confirm(`حذف ${d.name}؟ يفضل تعطيله إذا لديه حجوزات.`))return;const r=await supabase.from("rental_drones").delete().eq("id",d.id);if(r.error)setError("تعذر الحذف بسبب وجود حجوزات مرتبطة");else setDrones(a=>a.filter(x=>x.id!==d.id))}
 async function delBooking(id:number){if(!confirm("حذف الحجز نهائيًا؟"))return;const r=await supabase.from("rental_bookings").delete().eq("id",id);if(r.error)setError(r.error.message);else{setBookings(a=>a.filter(x=>x.id!==id));setSelected(null)}}
 return <div className="text-[#0F3A2B]" dir="rtl"><div className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-2xl font-black">إيجارات الدرون</h2><p className="text-sm text-gray-500">إدارة الدرونات والحجوزات والإيرادات</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="flex items-center gap-2 rounded-full border bg-white px-5 py-2.5 font-bold"><RefreshCw className="h-4 w-4"/>تحديث</button><button onClick={create} className="flex items-center gap-2 rounded-full bg-[#0F3A2B] px-5 py-2.5 font-bold text-white"><Plus className="h-4 w-4"/>إضافة درون</button></div></div>
 {error&&<div className="mb-5 rounded-2xl bg-red-50 p-4 font-bold text-red-700">{error}</div>}<div className="mb-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["إجمالي دخل الإيجار",`${stats.revenue.toFixed(3)} ر.ع`],["مجموع أيام الإيجار",`${stats.days} يوم`],["بانتظار التأكيد",String(stats.pending)],["إيجارات جارية",String(stats.active)],["الأكثر استئجارًا",stats.top]].map(([a,b])=><div key={a} className="rounded-3xl border bg-white p-5 shadow-sm"><p className="text-xs text-gray-500">{a}</p><p className="mt-2 text-2xl font-black">{b}</p></div>)}</div>
 <div className="mb-6 flex rounded-2xl bg-[#EAE4D8] p-1"><button onClick={()=>setSection("bookings")} className={`flex-1 rounded-xl py-3 font-black ${section==="bookings"?"bg-[#0F3A2B] text-white":""}`}>الحجوزات</button><button onClick={()=>setSection("drones")} className={`flex-1 rounded-xl py-3 font-black ${section==="drones"?"bg-[#0F3A2B] text-white":""}`}>درونات الإيجار</button></div>
 {loading?<div className="flex justify-center gap-2 rounded-3xl bg-white py-20"><Loader2 className="animate-spin"/>جاري التحميل...</div>:section==="bookings"?bookings.length===0?<div className="rounded-3xl bg-white p-12 text-center">لا توجد حجوزات</div>:<div className="overflow-x-auto rounded-3xl border bg-white shadow-xl"><table className="w-full min-w-[1200px] text-right text-sm"><thead className="bg-[#0F3A2B] text-white"><tr>{["رقم","الدرون","العميل","الهاتف","من","إلى","الأيام","الإجمالي","الحالة","التفاصيل"].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{bookings.map(b=><tr key={b.id} className="border-b"><td className="p-4 font-black">#{b.id}</td><td className="p-4 font-bold">{b.rental_drones?.name||"—"}</td><td className="p-4">{b.customer_name}</td><td className="p-4" dir="ltr">{b.phone}</td><td className="p-4">{b.start_date}</td><td className="p-4">{b.end_date}</td><td className="p-4">{b.total_days}</td><td className="p-4 font-black">{Number(b.total_amount).toFixed(3)} ر.ع</td><td className="p-4"><select value={b.status} onChange={e=>void status(b.id,e.target.value)} className={`rounded-full px-3 py-2 font-bold ${style(b.status)}`}>{STAT.map(s=><option value={s[0]} key={s[0]}>{s[1]}</option>)}</select></td><td className="p-4"><button onClick={()=>setSelected(b)} className="rounded-full bg-[#0F3A2B] px-5 py-2 text-white">عرض</button></td></tr>)}</tbody></table></div>:
 <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{drones.map(d=><article key={d.id} className="overflow-hidden rounded-3xl border bg-white shadow-sm">{d.image_url?<img src={d.image_url} className="aspect-[16/9] w-full object-cover"/>:<div className="flex aspect-[16/9] items-center justify-center bg-gray-50">بدون صورة</div>}<div className="p-5"><div className="flex justify-between"><h3 className="text-xl font-black">{d.name}</h3><span className={`rounded-full px-3 py-1 text-xs ${d.is_active?"bg-green-100 text-green-700":"bg-gray-100"}`}>{d.is_active?"نشط":"مخفي"}</span></div><p className="mt-3 min-h-[44px] text-sm text-gray-600">{d.description||"—"}</p><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#F8F7F2] p-3">اليومي<br/><b>{Number(d.daily_price).toFixed(3)} ر.ع</b></div><div className="rounded-2xl bg-[#F8F7F2] p-3">التأمين<br/><b>{Number(d.deposit_amount).toFixed(3)} ر.ع</b></div></div><div className="mt-4 flex gap-2"><button onClick={()=>editDrone(d)} className="flex flex-1 items-center justify-center gap-2 rounded-full bg-[#0F3A2B] py-2.5 text-white"><Pencil className="h-4 w-4"/>تعديل</button><button onClick={()=>void delDrone(d)} className="rounded-full bg-red-100 p-3 text-red-700"><Trash2 className="h-4 w-4"/></button></div></div></article>)}</div>}
 {show&&<div className="fixed inset-0 z-[99999] flex items-center justify-center overflow-y-auto bg-black/55 p-4"><form onSubmit={save} className="relative my-6 w-full max-w-2xl rounded-[30px] bg-white p-7"><button type="button" onClick={()=>setShow(false)} className="absolute left-5 top-5 rounded-full bg-gray-100 p-2"><X/></button><h3 className="mb-6 text-2xl font-black">{edit===null?"إضافة درون للإيجار":"تعديل الدرون"}</h3><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="اسم الدرون" className="mb-3 h-12 w-full rounded-2xl border bg-[#F8F7F2] px-4"/><div className="grid gap-3 sm:grid-cols-2"><input type="number" step=".001" value={form.daily_price} onChange={e=>setForm({...form,daily_price:e.target.value})} placeholder="السعر اليومي" className="h-12 rounded-2xl border bg-[#F8F7F2] px-4"/><input type="number" step=".001" value={form.deposit_amount} onChange={e=>setForm({...form,deposit_amount:e.target.value})} placeholder="التأمين" className="h-12 rounded-2xl border bg-[#F8F7F2] px-4"/></div><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="التفاصيل" className="mt-3 min-h-28 w-full rounded-2xl border bg-[#F8F7F2] p-4"/><label className="mt-3 flex cursor-pointer items-center justify-center gap-2 rounded-2xl border-2 border-dashed p-6"><ImagePlus/>{uploading?"جاري الرفع":"رفع صورة"}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void upload(e)} className="hidden"/></label>{form.image_url&&<img src={form.image_url} className="mt-3 h-40 w-full rounded-2xl object-cover"/>}<label className="mt-3 flex gap-2 rounded-2xl bg-[#F8F7F2] p-4"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/>إظهار في الموقع</label><button disabled={saving||uploading} className="mt-5 h-14 w-full rounded-full bg-[#0F3A2B] font-black text-white">{saving?"جاري الحفظ":"حفظ"}</button></form></div>}
 {selected&&<div className="fixed inset-0 z-[99999] flex items-center justify-center bg-black/55 p-4"><div className="relative w-full max-w-xl rounded-[30px] bg-white p-7"><button onClick={()=>setSelected(null)} className="absolute left-5 top-5 rounded-full bg-gray-100 p-2"><X/></button><h3 className="mb-5 text-2xl font-black">تفاصيل الحجز #{selected.id}</h3><div className="grid gap-3 sm:grid-cols-2">{[["الدرون",selected.rental_drones?.name||"—"],["العميل",selected.customer_name],["الهاتف",selected.phone],["الحالة",label(selected.status)],["من",selected.start_date],["إلى",selected.end_date],["الأيام",String(selected.total_days)],["الإجمالي",`${Number(selected.total_amount).toFixed(3)} ر.ع`]].map(x=><div className="rounded-2xl bg-[#F8F7F2] p-4" key={x[0]}><small className="text-gray-500">{x[0]}</small><p className="font-black">{x[1]}</p></div>)}</div><p className="mt-4 rounded-2xl bg-[#F8F7F2] p-4">{selected.notes||"لا توجد ملاحظات"}</p><div className="mt-4 flex gap-3"><select value={selected.status} onChange={e=>void status(selected.id,e.target.value)} className={`flex-1 rounded-2xl px-4 font-bold ${style(selected.status)}`}>{STAT.map(s=><option value={s[0]} key={s[0]}>{s[1]}</option>)}</select><button onClick={()=>void delBooking(selected.id)} className="rounded-2xl bg-red-100 px-5 py-3 font-bold text-red-700"><Trash2/></button></div></div></div>}
 </div>}
