-- Phase 1: Admin Dashboard – categories & products tables
-- ==========================================================

-- ── updated_at trigger function ────────────────────────────
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- ── categories ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.categories (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  slug       TEXT UNIQUE,
  image_url  TEXT,
  sort_order INT DEFAULT 0,
  is_active  BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_categories_updated_at ON public.categories;
CREATE TRIGGER trg_categories_updated_at
  BEFORE UPDATE ON public.categories
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX IF NOT EXISTS idx_categories_is_active  ON public.categories (is_active);
CREATE INDEX IF NOT EXISTS idx_categories_sort_order ON public.categories (sort_order);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "categories_public_read"  ON public.categories;
DROP POLICY IF EXISTS "categories_auth_insert"  ON public.categories;
DROP POLICY IF EXISTS "categories_auth_update"  ON public.categories;
DROP POLICY IF EXISTS "categories_auth_delete"  ON public.categories;

CREATE POLICY "categories_public_read"
  ON public.categories FOR SELECT
  USING (true);

CREATE POLICY "categories_auth_insert"
  ON public.categories FOR INSERT
  WITH CHECK (auth.role() IN ('authenticated', 'service_role'));

CREATE POLICY "categories_auth_update"
  ON public.categories FOR UPDATE
  USING (auth.role() IN ('authenticated', 'service_role'));

CREATE POLICY "categories_auth_delete"
  ON public.categories FOR DELETE
  USING (auth.role() IN ('authenticated', 'service_role'));

-- ── products ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.products (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  slug        TEXT UNIQUE,
  description TEXT,
  price       NUMERIC(10,2) NOT NULL DEFAULT 0,
  image_url   TEXT,
  quantity    INT NOT NULL DEFAULT 0,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  colors      JSONB NOT NULL DEFAULT '[]'::JSONB,
  is_active   BOOLEAN DEFAULT TRUE,
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_at  TIMESTAMPTZ DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_products_updated_at ON public.products;
CREATE TRIGGER trg_products_updated_at
  BEFORE UPDATE ON public.products
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX IF NOT EXISTS idx_products_category_id ON public.products (category_id);
CREATE INDEX IF NOT EXISTS idx_products_is_active   ON public.products (is_active);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "products_public_read"  ON public.products;
DROP POLICY IF EXISTS "products_auth_insert"  ON public.products;
DROP POLICY IF EXISTS "products_auth_update"  ON public.products;
DROP POLICY IF EXISTS "products_auth_delete"  ON public.products;

CREATE POLICY "products_public_read"
  ON public.products FOR SELECT
  USING (true);

CREATE POLICY "products_auth_insert"
  ON public.products FOR INSERT
  WITH CHECK (auth.role() IN ('authenticated', 'service_role'));

CREATE POLICY "products_auth_update"
  ON public.products FOR UPDATE
  USING (auth.role() IN ('authenticated', 'service_role'));

CREATE POLICY "products_auth_delete"
  ON public.products FOR DELETE
  USING (auth.role() IN ('authenticated', 'service_role'));
