-- Phase 1: Admin Dashboard – discount codes, shipping, site settings, theme
-- =========================================================================

-- ── discount_codes ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.discount_codes (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          TEXT NOT NULL UNIQUE,
  discount_type TEXT NOT NULL DEFAULT 'percentage' CHECK (discount_type IN ('percentage','fixed')),
  discount_value NUMERIC(10,2) NOT NULL DEFAULT 0,
  min_order      NUMERIC(10,2),
  max_uses       INT,
  used_count     INT NOT NULL DEFAULT 0,
  starts_at      TIMESTAMPTZ,
  expires_at     TIMESTAMPTZ,
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ DEFAULT now(),
  updated_at     TIMESTAMPTZ DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_discount_codes_updated_at ON public.discount_codes;
CREATE TRIGGER trg_discount_codes_updated_at
  BEFORE UPDATE ON public.discount_codes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.discount_codes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "discount_codes_public_read"  ON public.discount_codes;
DROP POLICY IF EXISTS "discount_codes_auth_write"   ON public.discount_codes;

CREATE POLICY "discount_codes_public_read"
  ON public.discount_codes FOR SELECT USING (true);

CREATE POLICY "discount_codes_auth_write"
  ON public.discount_codes FOR ALL
  USING (auth.role() IN ('authenticated','service_role'))
  WITH CHECK (auth.role() IN ('authenticated','service_role'));

-- ── shipping_methods ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.shipping_methods (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key        TEXT NOT NULL UNIQUE,
  label      TEXT NOT NULL,
  price      NUMERIC(10,2) NOT NULL DEFAULT 0,
  duration   TEXT,
  sort_order INT DEFAULT 0,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_shipping_methods_updated_at ON public.shipping_methods;
CREATE TRIGGER trg_shipping_methods_updated_at
  BEFORE UPDATE ON public.shipping_methods
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.shipping_methods ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "shipping_methods_public_read" ON public.shipping_methods;
DROP POLICY IF EXISTS "shipping_methods_auth_write"  ON public.shipping_methods;

CREATE POLICY "shipping_methods_public_read"
  ON public.shipping_methods FOR SELECT USING (true);

CREATE POLICY "shipping_methods_auth_write"
  ON public.shipping_methods FOR ALL
  USING (auth.role() IN ('authenticated','service_role'))
  WITH CHECK (auth.role() IN ('authenticated','service_role'));

-- default rows (inserted only once)
INSERT INTO public.shipping_methods (key, label, price, duration, sort_order)
VALUES
  ('office', 'توصيل للمكتب', 1.00, '2-4 أيام عمل', 0),
  ('home',   'توصيل للمنزل', 2.00, '2-4 أيام عمل', 1)
ON CONFLICT (key) DO NOTHING;

-- ── site_settings ───────────────────────────────────────────────────────────
-- Generic key/value store for bank transfer info and other settings.
CREATE TABLE IF NOT EXISTS public.site_settings (
  key        TEXT PRIMARY KEY,
  value      TEXT,
  updated_at TIMESTAMPTZ DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_site_settings_updated_at ON public.site_settings;
CREATE TRIGGER trg_site_settings_updated_at
  BEFORE UPDATE ON public.site_settings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "site_settings_public_read" ON public.site_settings;
DROP POLICY IF EXISTS "site_settings_auth_write"  ON public.site_settings;

CREATE POLICY "site_settings_public_read"
  ON public.site_settings FOR SELECT USING (true);

CREATE POLICY "site_settings_auth_write"
  ON public.site_settings FOR ALL
  USING (auth.role() IN ('authenticated','service_role'))
  WITH CHECK (auth.role() IN ('authenticated','service_role'));

-- default bank transfer values
INSERT INTO public.site_settings (key, value) VALUES
  ('bank_account_name',         'HAMAD################BAL'),
  ('bank_account_number',       '0401063526560013'),
  ('bank_transfer_number',      '90977867'),
  ('bank_payment_instructions', 'يرجى التحويل على الحساب أعلاه ورفع صورة الإيصال لإتمام الطلب.')
ON CONFLICT (key) DO NOTHING;

-- ── theme_settings ──────────────────────────────────────────────────────────
-- Stores CSS variable values. key = CSS variable name (without --), value = CSS value.
CREATE TABLE IF NOT EXISTS public.theme_settings (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_theme_settings_updated_at ON public.theme_settings;
CREATE TRIGGER trg_theme_settings_updated_at
  BEFORE UPDATE ON public.theme_settings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.theme_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "theme_settings_public_read" ON public.theme_settings;
DROP POLICY IF EXISTS "theme_settings_auth_write"  ON public.theme_settings;

CREATE POLICY "theme_settings_public_read"
  ON public.theme_settings FOR SELECT USING (true);

CREATE POLICY "theme_settings_auth_write"
  ON public.theme_settings FOR ALL
  USING (auth.role() IN ('authenticated','service_role'))
  WITH CHECK (auth.role() IN ('authenticated','service_role'));

-- default theme values matching the existing design
INSERT INTO public.theme_settings (key, value) VALUES
  ('color-primary',    '#0F3A2B'),
  ('color-secondary',  '#2F6B4E'),
  ('color-background', '#F8F7F2'),
  ('color-button',     '#0F3A2B'),
  ('color-text',       '#0F3A2B'),
  ('color-border',     '#D8D2C5'),
  ('color-card',       '#FFFFFF'),
  ('border-radius',    '1rem'),
  ('shadow-style',     'soft'),
  ('font-family',      'inherit'),
  ('font-size-base',   '16px')
ON CONFLICT (key) DO NOTHING;

-- ── helper RPC: increment coupon used_count ─────────────────────────────────
CREATE OR REPLACE FUNCTION public.increment_coupon_used_count(coupon_id BIGINT)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  UPDATE public.discount_codes
  SET used_count = used_count + 1
  WHERE id = coupon_id;
END;
$$;
